#
# Copyright 2023 Roland Gisler, HSLU Informatik, Switzerland
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
default:
    image: maven:3.9.0-eclipse-temurin-17

variables:
    MAVEN_CLI_OPTS: "-s .mvn/settings.xml --batch-mode"
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
    paths:
        - .m2/repository
        - target

stages:
    - build
    - quality
    - deploy

build:
    stage: build
    script:
        - mvn $MAVEN_CLI_OPTS clean install $MAVEN_OPTS
        - java -jar ./config/jacocoreader-0.0.1.jar ./target/site/jacoco/index.html
    coverage: '/Total.*?([0-9]{1,3})%/'
    artifacts:
        paths:
            - target/site/jacoco/jacoco.xml
        reports:
            junit:
                - target/surefire-reports/TEST-*.xml
                - target/failsafe-reports/TEST-*.xml

coverage:
    stage: quality
    image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.9
    script:
        - python /opt/cover2cover.py target/site/jacoco/jacoco.xml $CI_PROJECT_DIR/src/main/java/ > target/site/cobertura.xml
    artifacts:
        reports:
            coverage_report:
                coverage_format: cobertura
                path: target/site/cobertura.xml


site:
    stage: deploy
    script:
        - mvn $MAVEN_CLI_OPTS site $MAVEN_OPTS
    only:
        - master
    artifacts:
        paths:
            - target/site/**
