name: TB AD Java Source

on: [pull_request, push]

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./I.BA_AD.F23/source/ad_java_source/

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate with Maven
        run: mvn validate

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./I.BA_AD.F23/source/ad_java_source/

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run the Maven verify phase
        working-directory: ./I.BA_AD.F23/source/ad_java_source/
        run: mvn --batch-mode --update-snapshots verify
