name: Build, Test & Lint AD rust source

on: [pull_request, push]

jobs:

  update_local_toolchain:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./I.BA_AD.F23/rust/algorithms-and-datastructures/
    steps:
      - uses: actions/checkout@v2

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install nightly

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version 

  lint_root:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./I.BA_AD.F23/rust/algorithms-and-datastructures/
    steps:
      - uses: actions/checkout@v2
                   
      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings          

  test_root:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./I.BA_AD.F23/rust/algorithms-and-datastructures/
    steps:
      - uses: actions/checkout@v2
                    
      - name: Test
        run: |
          cargo check
          cargo test --all

  build_root:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./I.BA_AD.F23/rust/algorithms-and-datastructures/
    steps:
      - uses: actions/checkout@v2
                    
      - name: Build
        run: |
          cargo build --release

  lint_edslib:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./I.BA_AD.F23/rust/algorithms-and-datastructures/edslib/
    steps:
      - uses: actions/checkout@v2
                   
      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings          

  test_edslib:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./I.BA_AD.F23/rust/algorithms-and-datastructures/edslib/
    steps:
      - uses: actions/checkout@v2
                    
      - name: Test
        run: |
          cargo check
          cargo test --all

  build_edslib:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./I.BA_AD.F23/rust/algorithms-and-datastructures/edslib/
    steps:
      - uses: actions/checkout@v2
                    
      - name: Build
        run: |
          cargo build --release

  lint_common:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./I.BA_AD.F23/rust/algorithms-and-datastructures/common/
    steps:
      - uses: actions/checkout@v2
                   
      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings          

  test_common:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./I.BA_AD.F23/rust/algorithms-and-datastructures/common/
    steps:
      - uses: actions/checkout@v2
                    
      - name: Test
        run: |
          cargo check
          cargo test --all

  build_common:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./I.BA_AD.F23/rust/algorithms-and-datastructures/common/
    steps:
      - uses: actions/checkout@v2
                    
      - name: Build
        run: |
          cargo build --release