name: LTB AD Rust Source

on: [pull_request, push]

jobs:

  setup_local_toolchain:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./I.BA_AD.F23/rust/algorithms-and-datastructures/
    steps:
      - uses: actions/checkout@v2

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install nightly

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version 

  lint_rust_source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
                   
      - name: Lint Root
        working-directory: ./I.BA_AD.F23/rust/algorithms-and-datastructures/
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings

      - name: Lint edslib
        working-directory: ./I.BA_AD.F23/rust/algorithms-and-datastructures/edslib/
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings

      - name: Lint common
        working-directory: ./I.BA_AD.F23/rust/algorithms-and-datastructures/common/
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings

  test_rust_source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test Root
        working-directory: ./I.BA_AD.F23/rust/algorithms-and-datastructures/
        run: |
          cargo check
          cargo test --all

      - name: Test edslib
        working-directory: ./I.BA_AD.F23/rust/algorithms-and-datastructures/edslib/
        run: |
          cargo check
          cargo test --all

      - name: Test common
        working-directory: ./I.BA_AD.F23/rust/algorithms-and-datastructures/common/
        run: |
          cargo check
          cargo test --all

  build_rust_source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build common
        working-directory: ./I.BA_AD.F23/rust/algorithms-and-datastructures/common/
        run: |
          cargo build --release

      - name: Build edslib
        working-directory: ./I.BA_AD.F23/rust/algorithms-and-datastructures/edslib/
        run: |
          cargo build --release
                    
      - name: Build Root
        working-directory: ./I.BA_AD.F23/rust/algorithms-and-datastructures/
        run: |
          cargo build --release