name: AD Rust - Cargo Build & Test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test_root:
    name: Rust project - latest
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./I.BA_AD.F23/rust/algorithms-and-datastructures/
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: cd ""
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose
